### ISSUE TITLE
Type hint arguments

### ISSUE THREAD

**Issue by levidurfee** [bulldogcreative/strype#3]
Go through and type hint arguments. `string`, `int`, `bool`, and anything else.

**Comment by insolution4** [comment]
I'd like to help you with that. What should I do? Should I fork it first?

**Comment by insolution4** [comment]
Would you like to have question marks like php 7.1 allows?
for exsample:
    public function chargeCustomer(CustomerInterface $customer, int $amount, ?string $key = null)

**Comment by levidurfee** [comment]
Hi @insolution4 ! I'm going to be making some big changes tomorrow, but after that, I would love your help. And yes, I think the `?` would be nice.

**Comment by levidurfee** [comment]
And yes, please fork the repo. Then when you're ready, create a Pull Request so I can review the changes.

**Comment by insolution4** [comment]
ok, write me when you finish your changes

**Comment by levidurfee** [comment]
@insolution4 You can start :)

**Comment by insolution4** [comment]
When I do not know int or double should be used, I use int

public function __construct(int $percentage)

you can correct it afterwards

**Comment by insolution4** [comment]
Done. I hope it will be useful

**Comment by levidurfee** [comment]
Very helpful! Thank you!
